language: node.js
node_js:
  - 11
  - 12
  - 13
cache:
  directories:
    - node_modules
sudo: required

notifications:
  email: false
addons:
  chrome: stable

jobs:
  include:
    - stage: test
      install:
        - npm i
      script:
        - npm test
